// src/components/AuthForm.vue
<template>
    <form @submit.prevent="$emit('handler', { username, email, password, isSignUp: isSignUpLocal })" class="w-100 bg-white p-5 rounded-lg lg:rounded-none">
        <h1 class="text-blue-400 text-2xl md:text-3xl lg:text-4xl font-semibold">{{ isSignUpLocal ? 'Sign Up' : 'Sign In' }}</h1>
        <h1 class="text-xl md:text-2xl lg:text-3xl font-semibold">
            Bookmark Management
        </h1>
         <!--Register flag-->
        <div v-if="isSignUpLocal" class="border border-gray-300 w-full p-3 mt-5 rounded-lg flex items-center gap-3">
            <CiUser/>
            <input v-model="username" type="text" class="w-full outline-none" placeholder="Username"/>
        </div>
        <div class="border border-gray-300 w-full p-3 mt-5 rounded-lg flex items-center gap-3">
            <CiMail/>
            <input v-model="email" type="email" class="w-full outline-none" placeholder="Email"/>
        </div>
        <div class="border border-gray-300 w-full p-3 mt-5 rounded-lg flex items-center gap-3">
            <CiLock/>
            <input v-model="password" type="password" class="w-full outline-none" placeholder="Password"/>
        </div>
        <button v-if="!isSignUpLocal" class="mt-5 text-gray-400 hover:text-gray-500 focus:text-gray-500 cursor-pointer">Forgot Password?</button>
        <button type="submit" class="w-full text-white p-3 bg-blue-400 mt-5 rounded-lg hover:bg-blue-500 focus:bg-blue-500">
            {{ isSignUpLocal ? 'Sign Up' : 'Sign In' }}
        </button>
        <p v-if="!isSignUpLocal" class="mt-5 text-gray-400 text-center">
            Don't have an account? <span @click="$emit('update:isSignUp', true)" class="text-blue-400 hover:text-blue-500 focus:text-blue-500 cursor-pointer">Sign Up</span>
        </p>
        <!--Register flag-->
        <button v-if="isSignUpLocal" @click="$emit('update:isSignUp', false)" type="button" class="w-full text-white p-3 bg-green-400 mt-5 rounded-lg hover:bg-green-500 focus:bg-green-500">Back</button>
    </form>
</template>
<script setup>
    import { CiUser, CiLock, CiMail } from 'vue-icons-plus/ci';
    import { ref, computed } from 'vue';
    const props = defineProps({ isSignUp: Boolean })
    const username = ref('');
    const email = ref('');
    const password = ref('');
    const isSignUpLocal = computed(() => props.isSignUp)
    defineEmits(['handler','update:isSignUp']);
</script>

// src/components/auth/AuthForm.tsx
import { CiUser, CiMail, CiLock } from "react-icons/ci";
import Input from "../input/Input";

type AuthFormProps = {
    username: string;
    email: string;
    password: string;
    usernameChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    emailChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    passwordChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    submit: (e: React.FormEvent<HTMLFormElement>) => void;
    setSignUpCheck: (value: boolean) => void;
    isSignUpCheck: boolean;
}
export default function AuthForm({ username, email, password, usernameChange, emailChange, passwordChange, submit, setSignUpCheck, isSignUpCheck }: AuthFormProps) {
    return (
        <form className="bg-white p-5 rounded-lg w-100 border border-gray-300 lg:border-none" onSubmit={submit}>
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-semibold">
                Bookmark Management <span className="text-purple-400">Sign In</span>
            </h1>
            {isSignUpCheck && (
                <Input
                    typeInput="withIcon"
                    className="mt-3"
                    icons={<CiUser className="text-lg md:text-xl lg:text-2xl"/>}
                    placeholder="Username"
                    type="text"
                    value={username}
                    onChange={usernameChange}
                />
            )}
            <Input 
                typeInput="withIcon"
                className="mt-3"
                icons={<CiMail className="text-lg md:text-xl lg:text-2xl"/>}
                placeholder="Email"
                type="email"
                value={email}
                onChange={emailChange}
            />
            <Input
                typeInput="withIcon"
                className="mt-3"
                icons={<CiLock className="text-lg md:text-xl lg:text-2xl"/>}
                placeholder="Password"
                type="password"
                value={password}
                onChange={passwordChange}
            />
            <button type="submit" className="mt-3 w-full rounded-lg p-3 bg-purple-400 text-white hover:bg-purple-500 focus:bg-purple-500">
                { isSignUpCheck ? 'Sign Up' : 'Sign In'}
            </button>
            {isSignUpCheck && (
                <button type="button" onClick={() => setSignUpCheck(false)} className="mt-3 w-full rounded-lg p-3 bg-purple-400 text-white hover:bg-purple-500 focus:bg-purple-500">
                    Back
                </button>
            )}
            {!isSignUpCheck && (
                <p className="text-center mt-3">
                    Don't have account? <span onClick={() => setSignUpCheck(true)} className="text-purple-400 hover:text-purple-500 focus:text-purple-500 cursor-pointer">Create new account</span>
                </p>
            )}
        </form>
    )
}
